name = "dune-base-designer"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dune-blueprints"
database_id = "fc4cb170-f638-4a62-a1d4-24b25a222186"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dune-blueprints"
