/**
 * ETL script: reads DT_DuneSocketSetupData.json + DT_BuildableGroupData_Building.json
 * and emits src/data/socketData.generated.ts with snap metadata.
 *
 * Run: npm run build:socket-data
 * Or:  SYSTEMS_DIR=/absolute/path npx tsx scripts/build-socket-data.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const SYSTEMS_DIR =
  process.env.SYSTEMS_DIR ??
  path.resolve(PROJECT_ROOT, '../dune-item-data/dune-awakening/Dune/Systems');

const SOCKET_FILE = path.join(SYSTEMS_DIR, 'Building/Data/DT_DuneSocketSetupData.json');
const GROUP_FILE  = path.join(SYSTEMS_DIR, 'Building/Data/BuildableGroupData/DT_BuildableGroupData_Building.json');
const OUT_FILE    = path.join(PROJECT_ROOT, 'src/data/socketData.generated.ts');

// ── Helpers ───────────────────────────────────────────────────────────────────

function shortType(objectName: string): string {
  const m = objectName.match(/'([^']+)'/);
  return m ? m[1] : objectName;
}

function quatYaw(qz: number, qw: number): number {
  return 2 * Math.atan2(qz, qw) * (180 / Math.PI);
}

function r2(n: number): number {
  return Math.round(n * 100) / 100;
}

// ── Load JSON ─────────────────────────────────────────────────────────────────

const socketJson = JSON.parse(fs.readFileSync(SOCKET_FILE, 'utf8')) as [{ Rows: Record<string, unknown> }];
const groupJson  = JSON.parse(fs.readFileSync(GROUP_FILE, 'utf8'))  as [{ Rows: Record<string, unknown> }];

const socketRows = socketJson[0].Rows as Record<string, {
  m_SocketSetupData: {
    m_SocketInstances: {
      Translation: { X: number; Y: number; Z: number };
      Rotation: { X: number; Y: number; Z: number; W: number };
      Scale3D: unknown;
    }[];
    m_PerInstanceStaticSocketData: {
      m_SocketTypes: { ObjectName: string }[];
      m_TargetSocketTypes: { ObjectName: string }[];
      m_SocketCosts: { Name: string };
      m_OverrideSocketRotations: unknown[];
    }[];
  };
}>;

const groupRows = groupJson[0].Rows as Record<string, {
  m_SocketSetup: { Name: string };
  m_BrushPlacementSnapRotation: string;
  m_BuildableBrushCornersShape: string;
  m_GhostFacingCameraAngleOffset: number;
}>;

// ── Extract socket setups ─────────────────────────────────────────────────────

const socketSetups: Record<string, {
  sockets: {
    lx: number; ly: number; lz: number;
    yawDeg: number;
    types: string[];
    targetTypes: string[];
    cost: string;
  }[];
}> = {};

for (const [name, row] of Object.entries(socketRows)) {
  const sdata = row.m_SocketSetupData;
  const instances = sdata.m_SocketInstances ?? [];
  const perInst   = sdata.m_PerInstanceStaticSocketData ?? [];

  const sockets = instances.map((inst, i) => {
    const pd = perInst[i];
    const rot = inst.Rotation;
    return {
      lx: r2(inst.Translation.X),
      ly: r2(inst.Translation.Y),
      lz: r2(inst.Translation.Z),
      yawDeg: r2(quatYaw(rot.Z, rot.W)),
      types:       pd ? pd.m_SocketTypes.map(t => shortType(t.ObjectName)) : [],
      targetTypes: pd ? pd.m_TargetSocketTypes.map(t => shortType(t.ObjectName)) : [],
      cost:        pd ? pd.m_SocketCosts.Name : 'No_Cost',
    };
  });

  socketSetups[name] = { sockets };
}

// ── Extract group data ────────────────────────────────────────────────────────

type SnapRotation = 'SnapOne' | 'SnapHalf' | 'SnapAll';
type CornersShape = 'Square' | 'TriangleEquilateral' | 'TriangleIsosceles' | 'Unknown';

const groupData: Record<string, {
  socketSetupName: string;
  snapRotation: SnapRotation;
  cornersShape: CornersShape;
  ghostCameraAngleOffset: number;
}> = {};

function parseSnap(s: string): SnapRotation {
  if (s.endsWith('SnapHalf')) return 'SnapHalf';
  if (s.endsWith('SnapAll'))  return 'SnapAll';
  return 'SnapOne';
}

function parseCorners(s: string): CornersShape {
  if (s.includes('TriangleEquilateral')) return 'TriangleEquilateral';
  if (s.includes('TriangleIsosceles'))   return 'TriangleIsosceles';
  if (s.includes('Square'))              return 'Square';
  return 'Unknown';
}

for (const [name, row] of Object.entries(groupRows)) {
  groupData[name] = {
    socketSetupName:        row.m_SocketSetup?.Name ?? '',
    snapRotation:           parseSnap(row.m_BrushPlacementSnapRotation ?? ''),
    cornersShape:           parseCorners(row.m_BuildableBrushCornersShape ?? ''),
    ghostCameraAngleOffset: row.m_GhostFacingCameraAngleOffset ?? 0,
  };
}

// ── Emit TypeScript ───────────────────────────────────────────────────────────

const lines: string[] = [
  '// AUTO-GENERATED by scripts/build-socket-data.ts — do not edit manually',
  '// Re-run: npm run build:socket-data',
  '',
  "export type SnapRotation = 'SnapOne' | 'SnapHalf' | 'SnapAll';",
  "export type CornersShape = 'Square' | 'TriangleEquilateral' | 'TriangleIsosceles' | 'Unknown';",
  '',
  'export interface SocketInstance {',
  '  lx: number; ly: number; lz: number; // local position in UE space',
  '  yawDeg: number; // outward-facing yaw (degrees)',
  '  types: string[];',
  '  targetTypes: string[];',
  '  cost: string; // Down | Up | Foundation_Edge | Sideways | No_Cost | ...',
  '}',
  '',
  'export interface GroupData {',
  '  socketSetupName: string;',
  '  snapRotation: SnapRotation;',
  '  cornersShape: CornersShape;',
  '  ghostCameraAngleOffset: number;',
  '}',
  '',
  `export const SOCKET_SETUPS: Record<string, { sockets: SocketInstance[] }> = ${JSON.stringify(socketSetups, null, 2)};`,
  '',
  `export const GROUP_DATA: Record<string, GroupData> = ${JSON.stringify(groupData, null, 2)};`,
];

fs.writeFileSync(OUT_FILE, lines.join('\n') + '\n', 'utf8');
console.log(`Wrote ${Object.keys(socketSetups).length} socket setups and ${Object.keys(groupData).length} group entries → ${OUT_FILE}`);
